"""shepherd-dialect: the Shepherd dialect over vcs-core's execution-mechanism SPI.

The run-driver home ratified 2026-06-10 (execplan §6 open decision 1): a lean
package built beside today's ``shepherd/``, importing only vcs-core's public
surfaces (``vcs_core.runtime_api`` + ``vcs_core.spi`` +
``vcs_core.runtime_substrate``).
"""

from importlib import import_module
from typing import Any

_EXPORTS: dict[str, tuple[str, str]] = {
    "ShepherdRunDriver": ("shepherd_dialect.run_driver", "ShepherdRunDriver"),
    "HERMES_REAUDIT_ON_BUMP": ("shepherd_dialect.providers.hermes", "HERMES_REAUDIT_ON_BUMP"),
    "HERMES_SUPPORTED_MODEL_PROVIDERS": ("shepherd_dialect.providers.hermes", "HERMES_SUPPORTED_MODEL_PROVIDERS"),
    "HERMES_TESTED_VERSION": ("shepherd_dialect.providers.hermes", "HERMES_TESTED_VERSION"),
    "CODEX_REAUDIT_ON_BUMP": ("shepherd_dialect.providers.codex_profile", "CODEX_REAUDIT_ON_BUMP"),
    "CODEX_TESTED_VERSION": ("shepherd_dialect.providers.codex_profile", "CODEX_TESTED_VERSION"),
    "Artifact": ("shepherd_dialect.nucleus", "Artifact"),
    "Check": ("shepherd_dialect.checks", "Check"),
    "CheckFailed": ("shepherd_dialect.checks", "CheckFailed"),
    "CHILD_LAUNCH_REFUSED": ("shepherd_dialect.trace", "CHILD_LAUNCH_REFUSED"),
    "CHILD_RUN_COMPLETED": ("shepherd_dialect.trace", "CHILD_RUN_COMPLETED"),
    "CHILD_VALUE_COMPLETED": ("shepherd_dialect.trace", "CHILD_VALUE_COMPLETED"),
    "ClaudeAgentProvider": ("shepherd_dialect.providers.claude_legacy", "ClaudeAgentProvider"),
    "ClaudeApiProvider": ("shepherd_dialect.providers.claude_api", "ClaudeApiProvider"),
    "ClaudeHeadlessProvider": ("shepherd_dialect.providers.claude_headless", "ClaudeHeadlessProvider"),
    "CodexAgentProvider": ("shepherd_dialect.providers.codex", "CodexAgentProvider"),
    "CodexAuthStatus": ("shepherd_dialect.providers.codex_profile", "CodexAuthStatus"),
    "CodexProfileError": ("shepherd_dialect.providers.codex_profile", "CodexProfileError"),
    "CompletedTask": ("shepherd_dialect.task_meta", "CompletedTask"),
    "CarrierCheckAuthority": ("shepherd_dialect.permission_plan", "CarrierCheckAuthority"),
    "DeliveryFailed": ("shepherd_dialect.nucleus", "DeliveryFailed"),
    "DeterministicFakeProvider": ("shepherd_dialect.providers.fake", "DeterministicFakeProvider"),
    "FileExists": ("shepherd_dialect.checks", "FileExists"),
    "HermesHeadlessProvider": ("shepherd_dialect.providers.hermes", "HermesHeadlessProvider"),
    "InRange": ("shepherd_dialect.checks", "InRange"),
    "Matches": ("shepherd_dialect.checks", "Matches"),
    "MaxLength": ("shepherd_dialect.checks", "MaxLength"),
    "MayResolution": ("shepherd_dialect.confinement", "MayResolution"),
    "ModelRuntimeOptions": ("shepherd_dialect.runtime_options", "ModelRuntimeOptions"),
    "NonEmpty": ("shepherd_dialect.checks", "NonEmpty"),
    "ProviderRuntimeOptions": ("shepherd_dialect.runtime_options", "ProviderRuntimeOptions"),
    "Run": ("shepherd_dialect.nucleus", "Run"),
    "RunRef": ("shepherd_dialect.nucleus", "RunRef"),
    "RunTrace": ("shepherd_dialect.trace", "RunTrace"),
    "ResolvedRuntimeView": ("shepherd_dialect.runtime_options", "ResolvedRuntimeView"),
    "RuntimeOptions": ("shepherd_dialect.runtime_options", "RuntimeOptions"),
    "RuntimeOptionsError": ("shepherd_dialect.runtime_options", "RuntimeOptionsError"),
    "SourceValidationError": ("shepherd_dialect.source_validation", "SourceValidationError"),
    "StepMetadata": ("shepherd_dialect.steps", "StepMetadata"),
    "StepOutputError": ("shepherd_dialect.steps", "StepOutputError"),
    "SupervisorDenied": ("shepherd_dialect.supervision", "SupervisorDenied"),
    "TaskRunEnvelope": ("shepherd_dialect.task_run_envelope", "TaskRunEnvelope"),
    "TaskRunEnvelopeError": ("shepherd_dialect.task_run_envelope", "TaskRunEnvelopeError"),
    "TaskMetadata": ("shepherd_dialect.task_meta", "TaskMetadata"),
    "TaskRef": ("shepherd_dialect.task_meta", "TaskRef"),
    "UnsupportedMayProfileError": ("shepherd_dialect.confinement", "UnsupportedMayProfileError"),
    "Workspace": ("shepherd_dialect.nucleus", "Workspace"),
    "append_run_trace": ("shepherd_dialect.trace", "append_run_trace"),
    "ask": ("shepherd_dialect.nucleus", "ask"),
    "build_run_trace_revision": ("shepherd_dialect.trace", "build_run_trace_revision"),
    "check_task_source": ("shepherd_dialect.source_validation", "check_task_source"),
    "claude_auth_mode": ("shepherd_dialect.providers.claude_auth", "claude_auth_mode"),
    "claude_auth_status": ("shepherd_dialect.providers.claude_auth", "claude_auth_status"),
    "adopt_existing_codex_login": ("shepherd_dialect.providers.codex_profile", "adopt_existing_codex_login"),
    "codex_auth_status": ("shepherd_dialect.providers.codex_profile", "codex_auth_status"),
    "hermes_auth_status": ("shepherd_dialect.providers.hermes", "hermes_auth_status"),
    "probe_claude_auth": ("shepherd_dialect.providers.claude_headless", "probe_claude_auth"),
    "login_codex_chatgpt": ("shepherd_dialect.providers.codex_profile", "login_codex_chatgpt"),
    "login_codex_api_key": ("shepherd_dialect.providers.codex_profile", "login_codex_api_key"),
    "logout_codex_profile": ("shepherd_dialect.providers.codex_profile", "logout_codex_profile"),
    "probe_codex_auth": ("shepherd_dialect.providers.codex_profile", "probe_codex_auth"),
    "probe_hermes_auth": ("shepherd_dialect.providers.hermes", "probe_hermes_auth"),
    "current_binding": ("shepherd_dialect.nucleus", "current_binding"),
    "deliver": ("shepherd_dialect.nucleus", "deliver"),
    "drafts_only_supervisor": ("shepherd_dialect.supervision", "drafts_only_supervisor"),
    "dump_task_args": ("shepherd_dialect.task_meta", "dump_task_args"),
    "emit_artifact": ("shepherd_dialect.nucleus", "emit_artifact"),
    "initialize_workspace": ("shepherd_dialect.host_bootstrap", "initialize_workspace"),
    "native_jail_available": ("shepherd_dialect.host_bootstrap", "native_jail_available"),
    "WorkspaceInitError": ("shepherd_dialect.host_bootstrap", "WorkspaceInitError"),
    "WorkspaceInitResult": ("shepherd_dialect.host_bootstrap", "WorkspaceInitResult"),
    "extract_checks": ("shepherd_dialect.checks", "extract_checks"),
    "extract_step_metadata": ("shepherd_dialect.steps", "extract_step_metadata"),
    "extract_task_metadata": ("shepherd_dialect.task_meta", "extract_task_metadata"),
    "extract_task_source": ("shepherd_dialect.task_meta", "extract_task_source"),
    "handle": ("shepherd_dialect.nucleus", "handle"),
    "load_task_args": ("shepherd_dialect.task_meta", "load_task_args"),
    "lower_may_to_confinement": ("shepherd_dialect.confinement", "lower_may_to_confinement"),
    "MonitorAssignment": ("shepherd_dialect.permission_plan", "MonitorAssignment"),
    "PermissionPlan": ("shepherd_dialect.permission_plan", "PermissionPlan"),
    "install_permission_plan": ("shepherd_dialect.permission_plan", "install"),
    "parse_step_output": ("shepherd_dialect.steps", "parse_step_output"),
    "parse_runtime_options": ("shepherd_dialect.runtime_options", "parse_runtime_options"),
    "parse_task_run_envelope": ("shepherd_dialect.task_run_envelope", "parse_task_run_envelope"),
    "read_run_trace": ("shepherd_dialect.trace", "read_run_trace"),
    "resolve_may": ("shepherd_dialect.confinement", "resolve_may"),
    "return_type_to_output_schema": ("shepherd_dialect.steps", "return_type_to_output_schema"),
    "step": ("shepherd_dialect.steps", "step"),
    "supervisor_frame": ("shepherd_dialect.supervision", "supervisor_frame"),
    "task": ("shepherd_dialect.nucleus", "task"),
    "task_input_model": ("shepherd_dialect.task_meta", "task_input_model"),
    "task_invocation_record": ("shepherd_dialect.trace", "task_invocation_record"),
    "task_prompt": ("shepherd_dialect.task_meta", "task_prompt"),
    "task_run_envelope_payload": ("shepherd_dialect.task_run_envelope", "task_run_envelope_payload"),
    "tell": ("shepherd_dialect.nucleus", "tell"),
    "validate_task_source": ("shepherd_dialect.source_validation", "validate_task_source"),
    "workspace": ("shepherd_dialect.nucleus", "workspace"),
}

__all__ = [
    "CHILD_LAUNCH_REFUSED",
    "CHILD_RUN_COMPLETED",
    "CHILD_VALUE_COMPLETED",
    "CODEX_REAUDIT_ON_BUMP",
    "CODEX_TESTED_VERSION",
    "HERMES_REAUDIT_ON_BUMP",
    "HERMES_SUPPORTED_MODEL_PROVIDERS",
    "HERMES_TESTED_VERSION",
    "Artifact",
    "CarrierCheckAuthority",
    "Check",
    "CheckFailed",
    "ClaudeAgentProvider",
    "ClaudeApiProvider",
    "ClaudeHeadlessProvider",
    "CodexAgentProvider",
    "CodexAuthStatus",
    "CodexProfileError",
    "CompletedTask",
    "DeliveryFailed",
    "DeterministicFakeProvider",
    "FileExists",
    "HermesHeadlessProvider",
    "InRange",
    "Matches",
    "MaxLength",
    "MayResolution",
    "ModelRuntimeOptions",
    "MonitorAssignment",
    "NonEmpty",
    "PermissionPlan",
    "ProviderRuntimeOptions",
    "ResolvedRuntimeView",
    "Run",
    "RunRef",
    "RunTrace",
    "RuntimeOptions",
    "RuntimeOptionsError",
    "ShepherdRunDriver",
    "SourceValidationError",
    "StepMetadata",
    "StepOutputError",
    "SupervisorDenied",
    "TaskMetadata",
    "TaskRef",
    "TaskRunEnvelope",
    "TaskRunEnvelopeError",
    "UnsupportedMayProfileError",
    "Workspace",
    "WorkspaceInitError",
    "WorkspaceInitResult",
    "adopt_existing_codex_login",
    "append_run_trace",
    "ask",
    "build_run_trace_revision",
    "check_task_source",
    "claude_auth_mode",
    "claude_auth_status",
    "codex_auth_status",
    "current_binding",
    "deliver",
    "drafts_only_supervisor",
    "dump_task_args",
    "emit_artifact",
    "extract_checks",
    "extract_step_metadata",
    "extract_task_metadata",
    "extract_task_source",
    "handle",
    "hermes_auth_status",
    "initialize_workspace",
    "install_permission_plan",
    "load_task_args",
    "login_codex_api_key",
    "login_codex_chatgpt",
    "logout_codex_profile",
    "lower_may_to_confinement",
    "native_jail_available",
    "parse_runtime_options",
    "parse_step_output",
    "parse_task_run_envelope",
    "probe_claude_auth",
    "probe_codex_auth",
    "probe_hermes_auth",
    "read_run_trace",
    "resolve_may",
    "return_type_to_output_schema",
    "step",
    "supervisor_frame",
    "task",
    "task_input_model",
    "task_invocation_record",
    "task_prompt",
    "task_run_envelope_payload",
    "tell",
    "validate_task_source",
    "workspace",
]


def __getattr__(name: str) -> Any:
    try:
        module_name, attr_name = _EXPORTS[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted((*globals(), *__all__))
